### ISSUE TITLE
Use and adaptation to another open source project

### ISSUE THREAD

**Issue by H-G-11** [srobbin01/daisyui-dashboard-template-dashwind#3]
Hello there,

I really like this app and am thankful for your work.

I am doing an open-source project (not yet released) for a full-stack app with:
- Backend in Python
- Frontend in Svelte
- ...and a few other things

Would you agree to me using your template, transformed in Svelte, for the UI? I would of course mention your repository.

There would be some significant changes, but the goal is to have a similar UI in the end.

Please let me know.

Thank you very much

**Comment by srobbin01** [comment]
Thank you, @HuguesGallier! I appreciate your positive feedback. 

You have my full permission to use the work in your project and make any needed adjustments.
